package com.vv.export.formatter.util;

/**
 * @author Vivek Verma
 * @since 30/8/20
 */
public class Constants {

    public static final String CORE_STR = "Attemptinggggggggggggggggggggggggggggggggggg " +
            "Filllllllllllllllllllllinggggggggggggggggggggg " +
            "uppppppppppppppppppppppppppppppppppppppp" +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "FUELLLLLLLLLLLLLLLLLLLLLLINGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG " +
            "\n";
    public static final String CORE_STR_FILE = "Filer";
    public static final Double FACTOR_KB = 1024.0;
    public static final Double FACTOR_MB = FACTOR_KB * FACTOR_KB;
    public static final Double FACTOR_GB = FACTOR_MB * FACTOR_KB;
    public static final int SLEEP_TIME_MONITORING_FILE = 10;
}
